// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using ctest.Models.dboSchema;


namespace ctest.Models.dboSchema;

[Table("ENCRYPTIONKEY")]
[Index("Valid", Name = "IX_ENCRYPTIONKEY_VALID", AllDescending = true)]
public partial class Encryptionkey
{
    [Key]
    [Column("ENCRYPTIONKEYID")]
    public long Encryptionkeyid { get; set; }

    [Column("CHATUSERID")]
    public long Chatuserid { get; set; }

    [Required]
    [Column("KEYVALUE")]
    [MaxLength(512)]
    public byte[] Keyvalue { get; set; }

    [Column("CREATEDAT", TypeName = "datetime")]
    public DateTime Createdat { get; set; }

    [Column("VALID")]
    public short Valid { get; set; }

    [Required]
    [Column("MOD_USER")]
    [StringLength(256)]
    public string ModUser { get; set; }

    [Column("MOD_TIMESTAMP", TypeName = "datetime")]
    public DateTime ModTimestamp { get; set; }

    [Required]
    [Column("CR_USER")]
    [StringLength(256)]
    public string CrUser { get; set; }

    [Column("CR_TIMESTAMP", TypeName = "datetime")]
    public DateTime CrTimestamp { get; set; }

    [ForeignKey("Chatuserid")]
    [InverseProperty("Encryptionkey")]
    public virtual Chatuser Chatuser { get; set; }
}