// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ctest.Models.dboSchema
{
    public partial class EncryptionKeyInsertResult
    {
        [Column("ENCRYPTIONKEYID", TypeName = "decimal(38,0)")]
        public decimal? ENCRYPTIONKEYID { get; set; }
    }
}
