// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ctest.Models.Configurations;
using ctest.Models.dboSchema;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
#nullable disable

namespace ctest.Models;

public partial class Test2Context : DbContext
{
    public Test2Context(DbContextOptions<Test2Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Chatuser> Chatuser { get; set; }

    public virtual DbSet<Encryptionkey> Encryptionkey { get; set; }

    public virtual DbSet<Message> Message { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new Configurations.ChatuserConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.EncryptionkeyConfiguration());
        modelBuilder.ApplyConfiguration(new Configurations.MessageConfiguration());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
